const API = [
  {
    id: 1,
    image: '../images/waltercolour-salt-1.jpg',
    name: 'Maggie',
    category: "Lunch",
    price: 25,
    description: "Dinner Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore neque ullam adipisci obcaecati amet architecto explicabo porro ab, rerum possimus necessitatibus reprehenderit eius ipsa pariatur veniam laboriosam! Porro, consequatur recusandae!",
  },
  {
    id: 2,
    image: '../images/waltercolour-salt-2.jpg',
    name: "Noodle",
    category: "Breakfast",
    price: 25,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore neque ullam adipisci obcaecati amet architecto explicabo porro ab, rerum possimus necessitatibus reprehenderit eius ipsa pariatur veniam laboriosam! Porro, consequatur recusandae!",
  },
  {
    id: 3,
    image: '../images/waltercolour-salt-3.jpg',
    name: "Samosa",
    category: "Breakfast",
    price: 25,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore neque ullam adipisci obcaecati amet architecto explicabo porro ab, rerum possimus necessitatibus reprehenderit eius ipsa pariatur veniam laboriosam! Porro, consequatur recusandae!",
  },
  {
    id: 4,
    image: '../images/waltercolour-salt-2.jpg',
    name: 'Merci',
    category: "Lunch",
    price: 25,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore neque ullam adipisci obcaecati amet architecto explicabo porro ab, rerum possimus necessitatibus reprehenderit eius ipsa pariatur veniam laboriosam! Porro, consequatur recusandae!",
  },
  {
    id: 5,
    image: '../images/waltercolour-salt-1.jpg',
    name: 'Aalu',
    category: "Dinner",
    price: 25,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore neque ullam adipisci obcaecati amet architecto explicabo porro ab, rerum possimus necessitatibus reprehenderit eius ipsa pariatur veniam laboriosam! Porro, consequatur recusandae!",
  },
  {
    id: 6,
    image: '../images/waltercolour-salt-3.jpg',
    name: 'Merci',
    category: "Evening",
    price: 25,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore neque ullam adipisci obcaecati amet architecto explicabo porro ab, rerum possimus necessitatibus reprehenderit eius ipsa pariatur veniam laboriosam! Porro, consequatur recusandae!",
  },
  {
    id: 7,
    image: '../images/waltercolour-salt-4.jpg',
    name: 'Merci',
    category: "Evening",
    price: 25,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore neque ullam adipisci obcaecati amet architecto explicabo porro ab, rerum possimus necessitatibus reprehenderit eius ipsa pariatur veniam laboriosam! Porro, consequatur recusandae!",
  },
  {
    id: 8,
    image: '../images/waltercolour-salt-1.jpg',
    name: 'Merci',
    category: "Evening",
    price: 25,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore neque ullam adipisci obcaecati amet architecto explicabo porro ab, rerum possimus necessitatibus reprehenderit eius ipsa pariatur veniam laboriosam! Porro, consequatur recusandae!",
  },
  {
    id: 9,
    image: '../images/waltercolour-salt-2.jpg',
    name: 'Merci',
    category: "Dinner",
    price: 25,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore neque ullam adipisci obcaecati amet architecto explicabo porro ab, rerum possimus necessitatibus reprehenderit eius ipsa pariatur veniam laboriosam! Porro, consequatur recusandae!",
  },
  {
    id: 10,
    image: '../images/waltercolour-salt-3.jpg',
    name: 'Merci',
    category: "Dinner",
    price: 25,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore neque ullam adipisci obcaecati amet architecto explicabo porro ab, rerum possimus necessitatibus reprehenderit eius ipsa pariatur veniam laboriosam! Porro, consequatur recusandae!",
  },
  {
    id: 11,
    image: '../images/waltercolour-salt-4.jpg',
    name: 'Merci',
    category: "Breakfast",
    price: 25,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore neque ullam adipisci obcaecati amet architecto explicabo porro ab, rerum possimus necessitatibus reprehenderit eius ipsa pariatur veniam laboriosam! Porro, consequatur recusandae!",
  },
  {
    id: 12,
    image: '../images/waltercolour-salt-1.jpg',
    name: 'Merci',
    category: "Breakfast",
    price: 25,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore neque ullam adipisci obcaecati amet architecto explicabo porro ab, rerum possimus necessitatibus reprehenderit eius ipsa pariatur veniam laboriosam! Porro, consequatur recusandae!",
  },
  {
    id: 13,
    image: '../images/waltercolour-salt-4.jpg',
    name: 'Merci',
    category: "Lunch",
    price: 25,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore neque ullam adipisci obcaecati amet architecto explicabo porro ab, rerum possimus necessitatibus reprehenderit eius ipsa pariatur veniam laboriosam! Porro, consequatur recusandae!",
  },
  {
    id: 14,
    image: '../images/waltercolour-salt-3.jpg',
    name: 'Merci',
    category: "Dinner",
    price: 25,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore neque ullam adipisci obcaecati amet architecto explicabo porro ab, rerum possimus necessitatibus reprehenderit eius ipsa pariatur veniam laboriosam! Porro, consequatur recusandae!",
  },
];
export default API;